#!/bin/bash
#BSUB -J "index_bamfiles"
#BSUB -R "rusage[mem=5000]"
#BSUB -n 1
#BSUB -W 2:00

## Load necessary modules
module load gcc/4.8.2 gdc bamtools/2.4.0

## Define sample names
all_samples=`cat ./results/demultiplexed/samples`

## Loop through all sorted quality filtered bamfiles and index each of them
for name in $all_samples
do
bamtools index -in ./results/mapped/samplesQ10/${name}_Q10.sort.bam
done
